export const CONNECT_PENDING = 'CONNECT_PENDING';
export const CONNECT_SUCCESS = 'CONNECT_SUCCESS';
export const CONNECT_FAILURE = 'CONNECT_FAILURE';

export const START_SCAN = 'START_SCAN';
export const STOP_SCAN = 'STOP_SCAN';
export const FOUND_SCAN = 'FOUND_SCAN';
export const SUBSCRIPTION_ON_DISCONNECTED = 'SUBSCRIPTION_ON_DISCONNECTED'

export const SET_WRITE_SUBCRIPTION = 'SET_WRITE_SUBCRIPTION'
export const SET_READ_SUBCRIPTION = 'SET_READ_SUBCRIPTION'

export const DISCONNECT_PENDING = 'DISCONNECT_PENDING';
export const DISCONNECT_SUCCESS = 'DISCONNECT_SUCCESS';
export const DISCONNECT_FAILURE = 'DISCONNECT_FAILURE';

export const SET_RX = 'SET_RX';
export const SET_DATA = 'SET_DATA';

export const LOG_WRITE = 'LOG_WRITE'
export const LOG_CLEAR = 'LOG_CLEAR'

export const SET_CHARACTERISTICS = 'SET_CHARACTERISTICS'

export const SET_VALUE = 'SET_VALUE'